### ISSUE TITLE
The first line of code blocks is indented slightly, and should not be.

### ISSUE THREAD

**Issue by Superbird11** [Prid13/Revert-StackExchange-Formatting#1]
With the extension enabled, default settings:

<img width="331" alt="Screen Shot 2020-08-29 at 10 26 37 PM" src="https://user-images.githubusercontent.com/12699114/91649912-de83a080-ea46-11ea-8637-c3960b3c9136.png">

With the extension disabled:

<img width="346" alt="Screen Shot 2020-08-29 at 10 28 14 PM" src="https://user-images.githubusercontent.com/12699114/91649921-f529f780-ea46-11ea-9bfb-fe55301add4e.png">

The first line of the code block seems to be indented by about 0.5em, for some reason. Successive lines are not indented.

[This](https://stackoverflow.com/questions/63653379/looking-for-the-easiest-way-to-convert-months-to-years-and-months-in-python/63653410#63653410) is the post used as an example of the bug.

**Comment by Prid13** [comment]
How did I not get notified of this issue?? No email, no notification, no nothing :/

Thanks for reporting! I've fixed the issue and updated my Chrome extension -- it takes 1-2 days to get it reviewed by Google, so until then :)

The problem was that code blocks share a CSS class with inline codes, so the padding rule for inline codes was also being applied to code blocks, hence the first line having a slight indent. Why only the first line? Because code blocks are inline elements (i.e. `display: inline;`), so only the first line was affected.

**Comment by Prid13** [comment]
**Update is live** on Chrome store :D
