### ISSUE TITLE
Fonts and font sizes

### ISSUE THREAD

**Issue by TedLyngmoVCC** [Prid13/Revert-StackExchange-Formatting#2]
The font and font-size just became unbearable on Stackoverflow (especially in code blocks). Is it be possible to extend this script to   fix that?

**Comment by Prid13** [comment]
Hi, I've just added this functionality and submitted the changes to Chrome Web Store. It should be live in a few hours at best :)

After the update, you should see an additional section to toggle reversions for Fonts. The first checkbox reverts all text fonts to *Arial*, while the second checkbox reverts all code blocks and inline codes to *Consolas* font:
![image](https://user-images.githubusercontent.com/27897747/119208606-57c69600-baa3-11eb-8322-4a2ef32b540d.png)

I'd been intending to add this functionality since the atrocious May 10th update on StackExchange websites, but due to religious festivites, family gatherings and national days, I was unable to work on this till recently. Thanks for reminding me and thanks for showing me that there are people wanting this update :)

I was on the verge of adding support for custom fonts as well, but that seemed like too much work so I just focused on this simple update for now. 😅

**Comment by Prid13** [comment]
It's [live](https://chrome.google.com/webstore/detail/revert-stackexchange-form/fliedkodjpgomjmjbkaehhlllnhmcjnh) :)

**Comment by TedLyngmoVCC** [comment]
Brilliant! Can't wait to get home to see how it looks on my Windows computer! Many thanks!

**Comment by TedLyngmo** [comment]
> Brilliant! Can't wait to get home to see how it looks on my Windows computer! Many thanks!

Verified working! Many thanks again!
